--------------------------------------------------------
--  Arquivo criado - segunda-feira-dezembro-18-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_PRODUTO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."T_PRODUTO" 
   (	"CD_PRODUTO" NUMBER, 
	"NM_PRODUTO" VARCHAR2(60 BYTE), 
	"VL_PRODUTO" NUMBER(9,2), 
	"DT_VALIDADE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.T_PRODUTO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index T_PRODUTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."T_PRODUTO_PK" ON "SYSTEM"."T_PRODUTO" ("CD_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table T_PRODUTO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."T_PRODUTO" MODIFY ("CD_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."T_PRODUTO" MODIFY ("NM_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."T_PRODUTO" MODIFY ("VL_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."T_PRODUTO" MODIFY ("DT_VALIDADE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."T_PRODUTO" ADD CONSTRAINT "T_PRODUTO_PK" PRIMARY KEY ("CD_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
